# -*- mode: python -*-
import os
# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()
objs = env.StaticObject('weighted_knn.cpp')
objs += env.SharedObject('weighted_knn.cpp')
env.aProgram(target = 'knn_offline', source= env.Glob("*.cpp"))
Return('objs')
